#!/bin/bash
# -*- coding: utf-8 -*-

DIR=$(dirname $(readlink -f ${BASH_SOURCE[0]}))

set -e +h

if [ -z "$1" ]; then
    echo "Usage: backup <command> [<args>]"
    exit 1
fi

if [ ! -e $DIR/$1.sh ]; then
    echo "$1: unrecognized command"
    exit 1
fi

$DIR/$1.sh ${@:2}

exit $?
