#!/bin/bash
# -*- coding: utf-8 -*-

DIR=$(dirname $(readlink -f ${BASH_SOURCE[0]}))

set -e +h

if [ -z "$1" ]; then
    echo "No command provided"
    exit 1
fi

if [ ! -e $DIR/$1.sh ]; then
    echo "Command '$1' not found"
    exit 1
fi

$DIR/$1.sh ${@:2}

exit $?
